### PR TITLE
use sentry options

### PR DESCRIPTION
**Pull request by chinskiy**
Greetings!

Like PR #10 it allows configuration but via `sentry.options`
I saw that PR #10 was more than year ago that's why I create new and make changes like in PR comments

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
This looks pretty nice, @dcramer I can resolve the conflicts if this looks good to you.

**Comment by dcramer** [comment]
I think I tried doing this elsewhere and the main concern is we can't call options.get at runtime. If we can refactor things to be in helper methods (see how the Slack/OAuth stuff looks in core) then I'm definitely +1

**Comment by EvanPurkhiser** [comment]
> we can't call options.get at runtime

Do you mean `options.register` ?

**Comment by dcramer** [comment]
@EvanPurkhiser nah, its the ``get()`` calls in the plugin code here

**Comment by EvanPurkhiser** [comment]
Oh I see, at module load time, yeah I see how you're doing it with slack in the new integrations stuff.

**Comment by dcramer** [comment]
This is super old, but I'd still love for us to be able to do this with integrations. We likely need to either address this with the options framework (might be tough/not doable), or make client_id/secret callable.

**Comment by dcramer** [comment]
Closing this as it'll be implemented as part of Sentry core. It could still be implemented in a third party plugin as the required changes upstream will also land as part of the referenced PR.

**Pull request closed without merging**
