### PR TITLE
domain doesn't seem to be provided.  Shouldn't we just key off the list of accepted domains?

### PR DESCRIPTION
**Pull request by rogerhu**
@dcramer

### CODE REVIEW

**Comment by rogerhu** [comment]
One other side note: I had to add myself as an organization member in order to complete the setup flow.

**Comment by dcramer** [comment]
@rogerhu this would break multi-org installs (specifically getsentry.com)

Domain would get set after first auth, though I definitely could see an issue with On-Prem installs and the missing membership. Let us look into that.

**Comment by rogerhu** [comment]
yeah i figured as much with you guys after PR'ng.  

So the sentry core stuff should pass in domain?

**Comment by dcramer** [comment]
@rogerhu basically what happens is on the setup pipeline it asks you to authenticate, and then when you do it binds domain in the internal AuthProvider config:

https://github.com/getsentry/sentry-auth-google/blob/master/sentry_auth_google/provider.py#L62

https://github.com/getsentry/sentry/blob/master/src/sentry/auth/helper.py#L456-L483

Code isnt overly clear here, and I think that comment isn't valid anymore (or at least its not clear to me what its referring to).

**Comment by dcramer** [comment]
Re: the membership stuff, I think the options we have are:

- Allow auth to be setup by non-members (a bit odd, should they become a member etc)
- Add a "Join Organization" button for superusers
- Add a CLI flow for forcing a user as an org member

It only matters for the first member, as after that anyone can SSO to gain permanent membership

**Comment by rogerhu** [comment]
Yrah the err uid mismatch for the org member lookup threw me off.  Maybe a different error message?

Confirmed.  Im able to get sso going by adding the member to the org.  Thanks for clarifying and releasing this code in general.

**Pull request closed without merging**
